meta_params:
  bands: ['delta', 'theta', 'alpha', 'beta', 'gamma']
  model_size: tiny
  experiment_name: pretrain_tiny_contextualizer
  run_name: pretrain_${meta_params.model_size}_contextualizer_train_size_${training_params.train_frac}_val_size_${training_params.val_frac}
  contextualizer_size: TINY
  log_system_metrics: True
  log_model_params_and_grads: False
  save_model: True
  save_final_model: True
patch_encoder_params:
  num_channels: 19
  sampling_rate: 128
  super_patch_seconds: 2
  hidden_gnn_mlp_ratio: 2
  n_gnn_transformer_layers: 3
  n_gnn_heads: 2
  num_subjects: 13190
  include_high: False
  channel_dropout_p: 0.1
contextualizer_params:
  contextualizer_layers: 6
training_params:
  input_dir: /storage/ice1/shared/bmed6780/mip_group_6/ef/TUH-128Hz
  pretrained_patch_encoder_dir: null
  train_frac: 0.9
  val_frac: 0.1   
  random_seed: 42
  learning_rate: 0.001
  l2_weight_decay: 0.001
  batch_size: 256
  epochs: 5
  T_max: 5
  eta_min: 1.0e-7
  scheduler_after_batch: False
  ckpt_dir: ./checkpoint
  num_workers: 32
  gradient_clip_value: 1e7
  autoencoder_ckpt_path: "./checkpoint/pretrained_autoencoder_no_high_out_dim_12/autoencoder_weights.pth"
  mask_ratio: 0.2
  weighted_random_sampler: False