meta_params:
  bands: ['delta', 'theta', 'alpha', 'beta', 'gamma', 'high']
  experiment_name: train_autoencoder
  run_name: train_autoencoder_train_size_${training_params.train_frac}_val_size_${training_params.val_frac}_layers_${patch_encoder_params.n_gnn_transformer_layers}_default
  log_system_metrics: False
  log_model_params_and_grads: False
  save_model: False
  save_final_model: True
  num_recons: 4
patch_encoder_params:
  num_channels: 19
  sampling_rate: 128
  super_patch_seconds: 2
  n_gnn_transformer_layers: 3
  hidden_gnn_mlp_ratio: 2
  n_gnn_heads: 2
  channel_dropout_p: 0.1
training_params:
  input_dir: /storage/ice1/shared/bmed6780/mip_group_6/ef/TUH-128Hz 
  train_frac: 0.9
  val_frac: 0.1
  random_seed: 42
  learning_rate: 1.0e-4
  l2_weight_decay: 1.0
  batch_size: 256
  epochs: 30
  T_max: 30
  eta_min: 1.0e-7
  scheduler_after_batch: False
  ckpt_dir: ./checkpoint
  num_workers: 32