meta_params:
  bands: ['delta', 'theta', 'alpha', 'beta', 'gamma']
  experiment_name: train_autoencoder
  save_model: False
  save_final_model: True
  run_name: train_autoencoder_train_size_${training_params.train_frac}_val_size_${training_params.val_frac}_seed_${training_params.random_seed}_${patch_encoder_params.n_gnn_transformer_layers}_layers
  log_system_metrics: False
  log_encoder_params_and_grads: False
  num_recons: 4
patch_encoder_params:
  num_channels: 19
  sampling_rate: 128
  super_patch_seconds: 2
  hop_length: 0.5
  delta_encoded_h: 4
  theta_encoded_h: 4
  alpha_encoded_h: 8
  beta_encoded_h: 16
  gamma_encoded_h: 32
  # high_encoded_h: 64
  n_gnn_transformer_layers: 2
training_params:
  input_dir: /storage/ice1/shared/bmed6780/mip_group_6/ef/TUH-128Hz 
  train_frac: 0.9
  val_frac: 0.1
  random_seed: 42
  learning_rate: 0.001
  l2_weight_decay: 0.0005
  batch_size: 512
  epochs: 10
  T_max: 10
  eta_min: 1.0e-7
  scheduler_after_batch: False
  ckpt_dir: ./checkpoint
  num_workers: 32
hydra:
  output_subdir: null
  mode: MULTIRUN
  sweeper:
    params:
      ++patch_encoder_params.n_gnn_transformer_layers: 3
      ++training_params.random_seed: 168, 210