python pretrain.py --input_dir=/home/hice1/mchen439/scratch/eegfoundationmodeldata \
 --input_dir_2=/home/hice1/mchen439/scratch/eegfoundationmodeldata2 \
 --train_frac=0.85 \
 --val_frac=0.15 \
 --learning_rate=0.001\
 --batch_size=256 \
 --training_epochs=10 \
 --ckpt_dir=./checkpoint \
 --load_from_ckpt=./checkpoint/batch_size256_30epochs \